---
# myrepo
https://git.example.ch/exmaple/myrepo:
  command: uname
  secret: mysecret-myrepo
  background: True
# test-repo
https://git.example.ch/exmaple/test-repo:
  command: uname
  secret: mysecret-test-repo
  background: True
